### PR TITLE
[Misc] Enabled JSON Logs & Added/Enhanced structured logs

### PR DESCRIPTION
**Pull request by anirudhprasad-sap**

### CODE REVIEW

**Comment by anirudhprasad-sap** [comment]
Example log during upgrade filtered using `sme.sap.com/btp-app-identifier-hash` -

I0426 11:36:06.609133   18178 reconcile-capapplicationversion.go:276] "Processing CAPApplicationVersion - Creating content job" name="cav-travelapp03-43" namespace="travelapp-01" contentJobName="cav-travelapp03-43-content" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:07.323887   18178 reconcile-capapplicationversion.go:584] "Processing CAPApplicationVersion - Creating deployment" name="cav-travelapp03-43" namespace="travelapp-01" deploymentName="cav-travelapp03-43-app-router" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:08.719563   18178 reconcile-capapplicationversion.go:584] "Processing CAPApplicationVersion - Creating deployment" name="cav-travelapp03-43" namespace="travelapp-01" deploymentName="cav-travelapp03-43-server" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:08.910429   18178 reconcile-capapplicationversion.go:401] "Processing CAPApplicationVersion - Creating service" name="cav-travelapp03-43" namespace="travelapp-01" serviceName="cav-travelapp03-43-additional-workload-svc" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:09.310197   18178 reconcile-capapplicationversion.go:401] "Processing CAPApplicationVersion - Creating service" name="cav-travelapp03-43" namespace="travelapp-01" serviceName="cav-travelapp03-43-app-router-svc" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:09.710877   18178 reconcile-capapplicationversion.go:401] "Processing CAPApplicationVersion - Creating service" name="cav-travelapp03-43" namespace="travelapp-01" serviceName="cav-travelapp03-43-server-svc" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:11.197579   18178 reconcile-capapplicationversion.go:584] "Processing CAPApplicationVersion - Creating deployment" name="cav-travelapp03-43" namespace="travelapp-01" deploymentName="cav-travelapp03-43-additional-workload" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:11.374820   18178 reconcile-capapplicationversion.go:464] "Processing CAPApplicationVersion - Creating network policy" name="cav-travelapp03-43" namespace="travelapp-01" networkPolicyName="cav-travelapp03-43" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:11.524773   18178 reconcile-capapplicationversion.go:464] "Processing CAPApplicationVersion - Creating network policy" name="cav-travelapp03-43" namespace="travelapp-01" networkPolicyName="cav-travelapp03-43--in" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:20.303116   18178 reconcile-captenant.go:428] "Processing CAPTenant - Creating CAPTenantOperations" name="cap-travelapp03-provider" namespace="travelapp-01" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:22.377136   18178 reconcile-captenantoperation.go:680] "Processing CAPTenantOperations - Creating job for custom tenant operation" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:27.834131   18178 reconcile-captenantoperation.go:304] "Processing CAPTenantOperations - Custom Tenant Operation Job finished" job="cap-travelapp03-provider-custom-op-6s95q" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:28.258715   18178 reconcile-captenantoperation.go:519] "Processing CAPTenantOperations - Creating job for tenant operation" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:37.667671   18178 reconcile-captenantoperation.go:302] "Processing CAPTenantOperations - Tenant Operation Job finished" job="cap-travelapp03-provider-tenant-job-gtbpk" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:37.961536   18178 reconcile-captenantoperation.go:680] "Processing CAPTenantOperations - Creating job for custom tenant operation" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:43.944839   18178 reconcile-captenantoperation.go:304] "Processing CAPTenantOperations - Custom Tenant Operation Job finished" job="cap-travelapp03-provider-custom-op-hlx6w" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

I0426 11:36:43.944958   18178 reconcile-captenantoperation.go:310] "Processing CAPTenantOperations - Completed CAPTenantOperations" namespace="travelapp-01" CAPTenantOperation="cap-travelapp03-provider-9t826" tenantID="da37c8e0-74d4-4382-b5e2-161c2900b82a" operation="upgrade" sme.sap.com/btp-app-identifier-hash="b5626da1be6a443abd9d65c372a943baa45e0b31"

**Comment by anirudhprasad-sap** [comment]
@Pavan-SAP One thing I noticed in the logs is that we are creating the service for the additional workload before creating the deployment itself. It is not causing any issues because we don't check if the workload is ready before creating the service. Shall I switch the order to keep it consistent? Also, should we start checking if the workload is ready before creating the service?

**Comment by Pavan-SAP** [comment]
Creating the service first was intentional considering scaling/scheduling etc.. 
So the way it is should be ok.. the service would anyway not work if the workload (deployment) isn't running. Let's not complicate things by adding these checks and use the default/built-in behaviour.

**Review by Pavan-SAP — APPROVED** [review]
✅

**Pull request merged**
